version: '2'
services:
    backend-app:
        image: backend
        external_links:
            - backend-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=BackEnd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    backend-mongodb:
        extends:
            file: mongodb.yml
            service: backend-mongodb
