version: '2'
services:
    backend-mongodb:
        container_name: backend-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/BackEnd/mongodb/:/data/db/
